config/routes.rb
Rails.application.routes.draw do
  root :to => "patients#home"
  get 'patients/index'
  get 'patients/show'
  get 'patients/new'
  get 'patients/edit'
  get 'patients/delete'
  get 'patients/home'

  resources :patients do
    member do
      get :delete
      get :show
      post :create
      post :edit
      get :qr_code
      get :vacc_rec
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
end

app/models/patient.rb
class Patient < ApplicationRecord
  #variable used to save patient image
  has_one_attached :avatar
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.order('title ASC')
  end

  def show
    @book = Book.find(params[:id])
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to(books_path, notice: "Added Book")
    else
      render('new')
    end

  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to(book_path(@book), notice: "Updated Book")
    else
      render('edit')
    end

  end

  def delete
    @book = Book.find(params[:id])
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to(books_path, notice: "Deleted Book")
  end

  private

    def book_params
      params.require(:book).permit(
        :title,
        :author,
        :genre,
        :price,
        :published_date
      )
    end


end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  require 'json'

  #list all patients in the index page
  def index
    @patients = Patient.order('last_name ASC')

    #find the latest patient made
    @id = Patient.maximum(:id)
    if(@id != nil)
      @patient = Patient.find(@id)
      File.open("public/patient_info.json", "w"){ |f| f << @patient.to_json}
    end
  end

  #patient to be shown in the show page
  def show
    @patient = Patient.find(params[:id])
  end

  #route to create new patient
  def new
    @patient = Patient.new
  end

  #create a new patient
  def create
    @patient = Patient.new(patient_params)
    # @patient.image_url = url_for(@patient.avatar)
    if @patient.save
      redirect_to(patients_path, notice: "Added Patient")
    else
      render('new')
    end

  end

  #route to edit patient information
  def edit
    @patient = Patient.find(params[:id])
  end

  #find and update existing patient data
  def update
    @patient = Patient.find(params[:id])
    @patient.avatar.attach(params[:avatar])
    # @patient.image_url = url_for(@patient.avatar)
    if @patient.update(patient_params)
      redirect_to(patients_path, notice: "Updated Patient")
    else
      render('edit')
    end

  end

  #route to delete patient information
  def delete
    @patient = Patient.find(params[:id])
  end

  #find and delete existing patient data
  def destroy
    @patient = Patient.find(params[:id])
    @patient.destroy
    redirect_to(patients_path, notice: "Deleted Patient")
  end

  #generate QR Code for selected patient
  def qr_code
    @patient = Patient.find(params[:id])
    @record_url = vacc_rec_patient_url(@patient)
    @qr = RQRCode::QRCode.new(@record_url, size: 10, level: :h)
    @png = @qr.as_png(
      bit_depth: 1,
      border_modules: 4,
      color_mode: ChunkyPNG::COLOR_GRAYSCALE,
      color: 'black',
      file: nil,
      fill: 'white',
      module_px_size: 6,
      resize_exactly_to: false,
      resize_gte_to: false,
      size: 400
    )
  end

  #patient shown in current vaccination record
  def vacc_rec
    @patient = Patient.find(params[:id])
  end

  private

  #parameters a patient possesses
  def patient_params
    params.require(:patient).permit(
      :first_name,
      :last_name,
      :dob,
      :address,
      :phone_number,
      :age,
      :vaccine_type,
      :state,
      :city,
      :gender,
      :avatar
    )
  end


end

app/helpers/application_helper.rb
module ApplicationHelper

  def error_messages_for(object)
    render(:partial => 'application/error_messages', :locals => {object => object})
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/collection_helper.rb
module CollectionHelper
end

app/views/application/_error_messages.html.erb
<!-- <%# if object && object.errors.size > 0 %>
    <div id="error-explanation">
      <h2><%#= pluralize(object.error.size, "error") %> prohibited from being saved</h2>
      <p>There were problems with the following fields:</p>
      <ul>
        <%# object.errors.full_messages.each do |msg| %>
        <li><%#= msg %></li>
          <%# end %>
      </ul>
    </div>
 <%# end %>-->

app/views/books/_form.html.erb
<%= error_messages_for(f.object) %>

<table summary="Book form fields">
  <tr>
    <th>Title</th>
    <td><%= f.text_field(:title) %></td>
  </tr>
  <tr>
    <th>Author</th>
    <td><%= f.text_field(:author) %></td>
  </tr>
  <tr>
    <th>Genre</th>
    <td><%= f.select(:genre, ['Fiction','Fantasy','Non-Fiction','Mystery','History','Science Fiction','Horror','Romance','Historical Fiction','Biography','Poetry'], :prompt => 'Select Genre') %></td>
  </tr>
  <tr>
    <th>Price</th>
    <td><%= f.number_field(:price, :step => "0.01") %></td>
  </tr>
  <tr>
    <th>Published-Date</th>
    <td><%= f.date_select(:published_date,{order: [:month, :day, :year], prompt: { day: 'Select day', month: 'Select month', year: 'Select year' }, start_year: Date.today.year, end_year: 1400}, {required: true}) %></td>
  </tr>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VaccinationTracker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/patients/_form.html.erb
<%= error_messages_for(f.object) %>
<!-- style sheet used for the patient info form -->
<style>
  .patient-table{
      margin: auto;
      text-align: center;
  }

  th, td{
      text-align: left;
      /*border: 3px solid green;*/
  }

  th{
      padding-right: 25px;
  }
</style>

<!-- ALl recorded patient information -->
<table summary="Patient form fields" class="patient-table">
  <tr>
    <th>First Name</th>
    <td><%= f.text_field(:first_name) %></td>
  </tr>
  <tr>
    <th>Last Name</th>
    <td><%= f.text_field(:last_name) %></td>
  </tr>
  <tr>
    <th>Date of Birth</th>
    <td><%= f.date_select(:dob,{order: [:month, :day, :year], prompt: { day: 'Select day', month: 'Select month', year: 'Select year' }, start_year: Date.today.year, end_year: 1400}, {required: true}) %></td>
  </tr>
  <tr>
    <th>Address</th>
    <td><%= f.text_field(:address) %></td>
  </tr>
  <tr>
    <th>City</th>
    <td><%= f.text_field(:city) %></td>
  </tr>
  <tr>
    <th>State</th>
    <td><%= f.text_field(:state) %></td>
  </tr>
  <tr>
    <th>Phone Number</th>
    <td><%= f.text_field(:phone_number) %></td>
  </tr>
  <tr>
    <th>Age</th>
    <td><%= f.number_field(:age) %></td>
  </tr>
  <tr>
    <th>Gender</th>
    <td><%= f.select(:gender, ['Male','Female','Other'], :prompt => 'Select Gender') %></td>
  </tr>
  <tr>
    <th>Vaccine Type</th>
    <td><%= f.select(:vaccine_type, ['Pfizer','Moderna','Johnson & Johnson'], :prompt => 'Select Type') %></td>
  </tr>
  <tr>
    <th>Upload Image</th>
      <td><%= f.file_field :avatar %></td>
  </tr>
</table>

app/views/patients/delete.html.erb
<!-- style sheet used for the delete page -->
<style>
  .patients-delete{
      margin: auto;
      text-align: center;
      width: 25%;
  }

  ul {
      list-style-type: none;
      margin: 0;
      padding: 0;
      overflow: hidden;
      border: 1px solid #e7e7e7;
      background-color: #500000;
  }

  li {
      float: left;
  }

  li a {
      display: block;
      color: white;
      text-align: center;
      padding: 14px 16px;
      text-decoration: none;
  }

  li a:hover:not(.active) {
      background-color: #d22c2c;
  }

</style>

<!-- navigation bar -->
<div class="navbar">
  <ul>
    <li><%= link_to("Home", patients_home_path) %></li>
    <li class="active"><%= link_to("Patients", patients_index_path) %></li>
  </ul>
</div>

<!-- Delete the Patient -->
<div class="patients-delete">
  <h2>Delete Patient</h2>

  <%= form_for(@patient, :method => 'delete') do |f| %>

    <p>Are you sure you want to permanently delete this Patient from the list?</p>
    <p><b><%= @patient.first_name %> <%= @patient.last_name %></b></p>

    <div class="form-buttons">
      <%= f.submit("Delete Patient") %>
    </div>

  <% end %>
</div>

app/views/patients/edit.html.erb
<!-- style sheet used for the edit page -->
<style>
  .patients-edit{
      margin: auto;
      text-align: center;
      width: 25%;
  }

  ul {
      list-style-type: none;
      margin: 0;
      padding: 0;
      overflow: hidden;
      border: 1px solid #e7e7e7;
      background-color: #500000;
  }

  li {
      float: left;
  }

  li a {
      display: block;
      color: white;
      text-align: center;
      padding: 14px 16px;
      text-decoration: none;
  }

  li a:hover:not(.active) {
      background-color: #d22c2c;
  }

</style>

<!-- navigation bar -->
<div class="navbar">
  <ul>
    <li><%= link_to("Home", patients_home_path) %></li>
    <li class="active"><%= link_to("Patients", patients_index_path) %></li>
  </ul>
</div>

<!-- Edit the Patient -->
<div class="patients-edit">
  <h2>Update Patient</h2>

  <%= form_for(@patient) do |f| %>

    <%= render(:partial =>'form', :locals => {:f => f}) %>

    <br>

    <div class="form-buttons">
      <%= f.submit("Update Patient Info") %>
    </div>

  <% end %>
</div>

app/views/patients/home.html.erb
<!-- style sheet used for the home page -->
<!DOCTYPE html>
<style>
    ul.navbar{
        list-style-type: none;
        margin: 0;
        padding: 0;
        overflow: hidden;
        border: 1px solid #e7e7e7;
        background-color: #500000;
    }

    li.navbar {
        float: left;
    }

    li.navbar a {
        display: block;
        color: white;
        text-align: center;
        padding: 14px 16px;
        text-decoration: none;
    }

    li.navbar a:hover:not(.active) {
        background-color: #d22c2c;
    }

    .home-info{
        /*border: 3px solid green;*/
        margin: auto;
        text-align: left;
        width: 25%;
    }
</style>

<!-- navigation bar -->
<html>
<div class="navbar">
  <ul class="navbar">
    <li class="navbar"><%= link_to("Home", patients_home_path) %></li>
    <li class="navbar"><%= link_to("Patients", patients_index_path) %></li>
  </ul>
</div>

<!-- App features/instructions -->
<div class="home-info">
  <h1>Welcome to Vaccination Tracker!</h1>

  <h3>How it works:</h3>
  <ul>
    <li>Click the patients tab to view a list of all vaccinated patients</li>
    <li>You can add, show, edit, and delete patients</li>
    <li>When updating a patient, please reupload an image</li>
    <li>You can also access a qr code for the patient to view their information</li>
  </ul>
</div>

</html>

app/views/patients/index.html.erb
<% # Links and scripts for datatables css %>
<link rel="stylesheet" type="text/css" href="https://ajax.aspnetcdn.com/ajax/jquery.dataTables/1.9.0/css/jquery.dataTables.css">
<link rel="stylesheet" type="text/css" href="https://ajax.aspnetcdn.com/ajax/jquery.dataTables/1.9.0/css/jquery.dataTables_themeroller.css">
<script type="text/javascript" charset="utf8" src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.7.1.min.js"></script>
<script type="text/javascript" charset="utf8" src="https://ajax.aspnetcdn.com/ajax/jquery.dataTables/1.9.0/jquery.dataTables.min.js"></script>
<script src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script src="https://cdn.datatables.net/1.10.24/js/jquery.dataTables.min.js"></script>

<!-- style sheet used for the index page -->
<html>
<head>

  <style>
      ul {
          list-style-type: none;
          margin: 0;
          padding: 0;
          overflow: hidden;
          border: 1px solid #e7e7e7;
          background-color: #500000;
      }

      li {
          float: left;
      }

      li a {
          display: block;
          color: white;
          text-align: center;
          padding: 14px 16px;
          text-decoration: none;
      }

      li a:hover:not(.active) {
          background-color: #d22c2c;
      }

      @import url('https://cdn.datatables.net/1.10.24/css/jquery.dataTables.min.css');
      td.details-control {
          background: url('https://www.datatables.net/examples/resources/details_open.png') no-repeat center center;
          cursor: pointer;
      }
      td.details-control:hover{
          background-color:#AF8B8B;
      }

      tr.shown td.details-control {
          background: url('https://www.datatables.net/examples/resources/details_close.png') no-repeat center center;
          background-color:#AF8B8B;
      }

      .patient_table_header{
          background-color:#500000;
          color:white;
      }

      .patient_index_title{
          text-align: center;
      }

      tr.odd{
          background-color:#DFD1D1 !important;
      }

      tr.even td.sorting_1{
          background-color:#DFD1D1 !important;
      }

      tr.odd td.sorting_1{
          background-color:#CFB9B9 !important;
      }

  </style>
</head>
</html>
<!-- navigation bar -->
<div class="navbar">
  <ul>
    <li><%= link_to("Home", patients_home_path) %></li>
    <li class="active"><%= link_to("Patients", patients_index_path) %></li>
  </ul>
</div>

<!-- List of Patients -->
<div>
  <h1 class="patient_index_title">Vaccinated Patients</h1>

  <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, class: "alert alert-info" %>
  <% end %>
  <%= link_to("Add New Patient", new_patient_path, :class => 'action new') %> <br>
  <br>
  <table class="listing" id="PatientList">
    <thead>
    <tr class="patient_table_header">
      <th></th>
      <th>Last Name</th>
      <th>First Name</th>
    </tr>
    </thead>
  </table>
</div>

<script>
    /* Formatting function for row details - ONGOING PATIENTS */
    function format( d ) {
        var showUrl=`/patients/${d['id']}`;
        var editUrl = `/patients/${d['id']}/edit`;
        var deleteUrl = `/patients/${d['id']}/delete`;
        var qrcodeUrl = `/patients/${d['id']}/qr_code`;


        // `d` is the original data object for the row
        var block = '<table cellpadding="5" cellspacing="0" border="0" style="padding-left:50px;">'+
            '<tr>'+
            '<td>Name:</td>'+
            '<td>'+d.first_name+ ' ' +d.last_name+ '</td>'+
            '</tr>'+
            '<tr>'+
            '<td>Phone Number:</td>'+
            '<td>'+d.phone_number+'</td>'+
            '</tr>'+
            '<tr>'+
            '<td>Age:</td>'+
            '<td>'+d.age+'</td>'+
            '</tr>'+
            '<tr>'+
            '<td>Actions:</td>'+
            '<td class="actions">'+
            `<a class='action show' href='${showUrl}'>Show</a>`+
            ' - '+
            `<a class='action show' href='${qrcodeUrl}'>QR Code</a>`+
            ' - '+
            `<a class='action show' href='${editUrl}'>Update</a>`+
            ' - '+
            `<a class='action show' href='${deleteUrl}'>Delete</a>`+
            '</td>'+
            '</tr>'+
            '</table>';

        return block;
    }


    $(document).ready(function() {
        var table = $('#PatientList').DataTable( {
            "data": <%= @patients.as_json.to_json.html_safe %>,
            "columns": [
                {
                    "className":      'details-control',
                    "orderable":      false,
                    "data":           null,
                    "defaultContent": ''
                },
                { "data": "last_name" },
                { "data": "first_name" }

            ],
            "order": [[1, 'asc']]
        } );
// Add event listener for opening and closing details
        $('#PatientList tbody').on('click', 'td.details-control', function () {
            var tr = $(this).closest('tr');
            var row = table.row( tr );
            if ( row.child.isShown() ) {
// This row is already open - close it
                row.child.hide();
                tr.removeClass('shown');
            }
            else {
// Open this row
                row.child( format(row.data()) ).show();
                tr.addClass('shown');
            }
        } );
    } );

</script>

app/views/patients/new.html.erb
<!-- style sheet used for the "new" page -->
<style>
  .patients-new{
      margin: auto;
      text-align: center;
  }

  ul {
      list-style-type: none;
      margin: 0;
      padding: 0;
      overflow: hidden;
      border: 1px solid #e7e7e7;
      background-color: #500000;
  }

  li {
      float: left;
  }

  li a {
      display: block;
      color: white;
      text-align: center;
      padding: 14px 16px;
      text-decoration: none;
  }

  li a:hover:not(.active) {
      background-color: #d22c2c;
  }

</style>

<!-- navigation bar -->
<div class="navbar">
  <ul>
    <li><%= link_to("Home", patients_home_path) %></li>
    <li class="active"><%= link_to("Patients", patients_index_path) %></li>
  </ul>
</div>

<!-- Make New Patient -->
<div class="patients-new">
  <h2>Add Patient</h2>

  <%= form_for(@patient, :url => patients_index_path, :method => 'post') do |f| %>

    <%= render(:partial =>'form', :locals => {:f => f}) %>
    <br>

    <div class="form-buttons">
      <%= f.submit("Add Patient") %>
    </div>

  <% end %>
</div>

app/views/patients/qr_code.html.erb
<!-- style sheet used for the QR Code page -->
<style>
  .qr-code{
      margin: auto;
      text-align: center;
      width: 25%;
  }

  ul {
      list-style-type: none;
      margin: 0;
      padding: 0;
      overflow: hidden;
      border: 1px solid #e7e7e7;
      background-color: #500000;
  }

  li {
      float: left;
  }

  li a {
      display: block;
      color: white;
      text-align: center;
      padding: 14px 16px;
      text-decoration: none;
  }

  li a:hover:not(.active) {
      background-color: #d22c2c;
  }
</style>

<!-- navigation bar -->
<div class="navbar">
  <ul>
    <li><%= link_to("Home", patients_home_path) %></li>
    <li class="active"><%= link_to("Patients", patients_index_path) %></li>
  </ul>
</div>

<!-- Display QR Code and Patient Name -->
<div class="qr-code">
  <h1>
    <%= @patient.first_name %>  <%= @patient.last_name %>
  </h1>

  <img src="<%= @png.to_data_url %>" />

  <br>
</div>

app/views/patients/show.html.erb
<!-- style sheet used for the show page -->
<style>
  .patients-show{
      margin: auto;
      text-align: center;
      width: 25%;
  }

  th, td{
      margin: auto;
      text-align: left;
      width: 50%;
  }

  .patient-table{
    margin: auto;
  }

  ul {
      list-style-type: none;
      margin: 0;
      padding: 0;
      overflow: hidden;
      border: 1px solid #e7e7e7;
      background-color: #500000;
  }

  li {
      float: left;
  }

  li a {
      display: block;
      color: white;
      text-align: center;
      padding: 14px 16px;
      text-decoration: none;
  }

  li a:hover:not(.active) {
      background-color: #d22c2c;
  }
</style>

<!-- navigation bar -->
<div class="navbar">
  <ul>
    <li><%= link_to("Home", patients_home_path) %></li>
    <li class="active"><%= link_to("Patients", patients_index_path) %></li>
  </ul>
</div>

<!-- Show the Patient Details -->
<div class="patients-show">

  <h2>View Patient</h2>

  <table summary="Patient detail view" class="patient-table">
    <tr>
      <th>First Name</th>
      <td><%= @patient.first_name %></td>
    </tr>
    <tr>
      <th>Last Name</th>
      <td><%= @patient.last_name %></td>
    </tr>
    <tr>
      <th>Date of Birth</th>
      <td><%= @patient.dob %></td>
    </tr>
    <tr>
      <th>Address</th>
      <td><%= @patient.address %></td>
    </tr>
    <tr>
      <th>City</th>
      <td><%= @patient.city %></td>
    </tr>
    <tr>
      <th>State</th>
      <td><%= @patient.state %></td>
    </tr>
    <tr>
      <th>Gender</th>
      <td><%= @patient.gender %></td>
    </tr>
    <tr>
      <th>Created</th>
      <td><%= @patient.created_at %></td>
    </tr>
    <tr>
      <th>Updated</th>
      <td><%= @patient.updated_at %></td>
    </tr>
  </table>
</div>

app/views/patients/vacc_rec.html.erb
<!-- style sheet used for the vaccination record page -->
<style>
    .patients-show{
        margin: auto;
        text-align: center;
    }

    th, td{
        margin: auto;
        text-align: left;
        width: 50%;
    }

    th{
        padding-right: 15px;
    }

    .patient-table{
        margin: auto;
    }

    ul {
        list-style-type: none;
        margin: 0;
        padding: 0;
        overflow: hidden;
        border: 1px solid #e7e7e7;
        background-color: #500000;
    }

    li {
        float: left;
    }

    li a {
        display: block;
        color: white;
        text-align: center;
        padding: 14px 16px;
        text-decoration: none;
    }

    li a:hover:not(.active) {
        background-color: #d22c2c;
    }

</style>

<!-- navigation bar -->
<div class="navbar">
  <ul>
    <li><%= link_to("Home", patients_home_path) %></li>
    <li class="active"><%= link_to("Patients", patients_index_path) %></li>
  </ul>
</div>

<!-- Show the Patient Vaccination Record -->
<div class="patients-show">

  <h2>View Patient</h2>

  <% if @patient.avatar.attached? %>
    <image style="width: 500px;" src="<%= (url_for(@patient.avatar)) %>"></image>
  <% end %>

  <table summary="Patient detail view" class="patient-table">
    <tr>
      <th>First Name</th>
      <td><%= @patient.first_name %></td>
    </tr>
    <tr>
      <th>Last Name</th>
      <td><%= @patient.last_name %></td>
    </tr>
    <tr>
      <th>Vaccination Type</th>
      <td><%= @patient.vaccine_type %></td>
    </tr>
  </table>
</div>